# Generated by Django 5.0.3 on 2024-05-07 11:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('client_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_mark', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subscribers', models.ManyToManyField(blank=True, null=True, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News_All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_or_art', models.CharField(choices=[('Нов', 'Новости'), ('Ст', 'Статья')], default='Нов', max_length=3)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(max_length=100)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('link_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_otm_Post_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.category')),
                ('link_otm_Post_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.news_all')),
            ],
        ),
        migrations.AddField(
            model_name='news_all',
            name='link_PostCategory',
            field=models.ManyToManyField(through='simpleapp.PostCategory', to='simpleapp.category'),
        ),
    ]
